[package]
name = "distrust-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
proc-macro = true

[dependencies]
lazy_static = "1.4.0"
syn = { version = "2.0.26", features=["full"] }
